export {default as Welcome} from './Welcome.vue'
export {default as HomeNav} from './HomeNav.vue'
export {default as Navbar} from './Navbar.vue'
export {default as Services} from './Services.vue'
export {default as Transactions} from './Transactions.vue'
export {default as Footer} from './Footer.vue'
